workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2

    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: Project.com.Algo-Trading
      vars:
        XCODE_WORKSPACE: "Algo-Trading.xcodeproj"
        XCODE_SCHEME: "Algo-Trading"
        APP_STORE_APP_ID: 1234567890  # Update with your App Store Connect app ID
      xcode: latest

    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: main
          include: true
          source: true
        - pattern: develop
          include: true
          source: true

    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles

      - name: Increment build number
        script: |
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-testflight-build-number "$APP_STORE_APP_ID" || echo 0)
          agvtool new-version -all $(($LATEST_BUILD_NUMBER + 1))

      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa \
            --project "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      email:
        recipients:
          - user@example.com  # Update with your email
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - Internal Testers

  ios-test-workflow:
    name: iOS Test Workflow
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      vars:
        XCODE_WORKSPACE: "Algo-Trading.xcodeproj"
        XCODE_SCHEME: "Algo-Trading"
      xcode: latest

    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: "*"
          include: true
          source: true

    scripts:
      - name: Run unit tests
        script: |
          xcodebuild test \
            -project "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -destination "platform=iOS Simulator,name=iPhone 16,OS=latest" \
            -resultBundlePath build/test-results.xcresult \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO
        test_report: build/test-results.xcresult

    artifacts:
      - build/test-results.xcresult
      - /tmp/xcodebuild_logs/*.log

    publishing:
      email:
        recipients:
          - user@example.com  # Update with your email
        notify:
          success: false
          failure: true
